Repository maykinmedia/open-inwoner, pull requests merged in 2024-10, with the labels that each got.

#1454 [#2823] Filter contactmomenten on Mijn Vragen based on kanaal
  src/open_inwoner/cms/cases/views/status.py
  src/open_inwoner/openzaak/tests/test_case_detail.py
Labels: release 1.22.1

#1462 [#2831] Fix contactform math captcha
  src/open_inwoner/components/templates/components/Contact/ContactForm.html
  src/open_inwoner/openklant/forms.py
  src/open_inwoner/openklant/tests/test_cms_plugins.py
  src/open_inwoner/openklant/tests/test_contactform.py
  src/open_inwoner/openklant/views/contactform.py
  src/open_inwoner/openklant/views/utils.py
  src/open_inwoner/utils/forms.py
  src/open_inwoner/utils/tests/test_form_fields.py
Labels: 1.22.2

#1456 [#2832] Rx.mission/Venray: Also show documents with the status archived
  src/open_inwoner/openzaak/tests/test_case_detail.py
  src/open_inwoner/openzaak/utils.py
Labels: venray-v3
