Repository maykinmedia/open-inwoner, pull requests merged in 2024-05, with the labels that each got.

#1189 :bug: [#2389] Activate Particulier Tab as default always
  src/open_inwoner/accounts/templates/registration/login.html
  src/open_inwoner/js/components/form/LoginForm.js
  src/open_inwoner/js/components/tab-panels/index.js
  src/open_inwoner/scss/components/TabPanel/TabPanel.scss
Labels: release 1.16.3

#1200 Upgrade to Debian bookworm in Dockerfile
  Dockerfile
Labels: release 1.16.3

#1198 [#2436] Fix optional 'medewerkerIdentificatie' in contactmoment POST
  src/open_inwoner/openklant/tests/test_contactform.py
  src/open_inwoner/openklant/views/contactform.py
Labels: release 1.16.3

#1182 [#2404] Avoid redirect cycle for DigiD login with email required
  src/open_inwoner/accounts/tests/test_auth.py
  src/open_inwoner/utils/middleware.py
Labels: release 1.16.3

#1191 :bug: [#2381] Make zakelijk tab hidden when eHerkenning is off
  src/open_inwoner/accounts/templates/registration/login.html
Labels: release 1.16.4

#1216 [#2465] Postprocess HTML for NLDS styling
  src/open_inwoner/pdc/tests/test_views.py
  src/open_inwoner/utils/ckeditor.py
Labels: release 1.17.2

#1231 Replace django-mailer with django-yubin
  requirements/base.in
  requirements/base.txt
  requirements/ci.txt
  requirements/dev.txt
  src/open_inwoner/conf/base.py
  src/open_inwoner/configurations/emails.py
  src/open_inwoner/configurations/tests/test_emails.py
Labels: release 1.17.2
