Repository maykinmedia/open-inwoner, pull requests merged in 2024-03, with the labels that each got.

#1083 [#2183] Fixed regression with optional status
  src/open_inwoner/openzaak/notifications.py
  src/open_inwoner/openzaak/tests/test_notification_utils.py
Labels: release 1.14.4

#1067 ♻️ [#2150] Throttle user emails based on template name
  src/open_inwoner/openzaak/managers.py
  src/open_inwoner/openzaak/migrations/0045_usercaseinfoobjectnotification_collision_key_and_more.py
  src/open_inwoner/openzaak/models.py
  src/open_inwoner/openzaak/notifications.py
  src/open_inwoner/openzaak/tests/test_models.py
  src/open_inwoner/openzaak/tests/test_notification_zaak_status.py
Labels: release 1.15

#1078 [#2175] Fix rounded corners for mail-templates
  src/open_inwoner/conf/parts/case_document_notification.html
  src/open_inwoner/conf/parts/case_status_notification.html
  src/open_inwoner/conf/parts/case_status_notification_action_required.html
  src/open_inwoner/static/mailcss/email.css
  src/open_inwoner/templates/mail/_base.html
Labels: release 1.15

#1085 :lipstick: [#2148] Make pagination conform to design
  src/open_inwoner/components/templates/components/Pagination/Pagination.html
  src/open_inwoner/scss/components/Pagination/Pagination.scss
Labels: release 1.15

#1059 [#2098] Show case-related questions in case detail view
  src/open_inwoner/accounts/views/contactmoments.py
  src/open_inwoner/cms/cases/tests/test_contactform.py
  src/open_inwoner/cms/cases/tests/test_htmx.py
  src/open_inwoner/cms/cases/urls.py
  src/open_inwoner/cms/cases/views/status.py
  src/open_inwoner/js/components/card/ToggleHideSelection.js
  src/open_inwoner/js/components/index.js
  src/open_inwoner/openklant/clients.py
  src/open_inwoner/openklant/tests/factories.py
  src/open_inwoner/openzaak/tests/test_case_detail.py
  src/open_inwoner/scss/components/Card/Card.scss
  src/open_inwoner/scss/components/Cases/CaseDetail.scss
  src/open_inwoner/scss/components/Contactmomenten/Contactmomenten.scss
  src/open_inwoner/templates/pages/cases/status_inner.html
  src/open_inwoner/templates/pages/contactmoment/list.html
  src/open_inwoner/templates/pages/questions/questions.html
Labels: release 1.15

#1075 ✨ [#2149] Display new answer header for mijn vragen list
  src/open_inwoner/accounts/views/contactmoments.py
  src/open_inwoner/apimock/apis/openklant-read/contactmomenten/contactmoment/aaaaaaaa-aaaa-aaaa-aaaa-bbbbbbbbbbb2.json
  src/open_inwoner/apimock/apis/openklant-read/contactmomenten/contactmoment/aaaaaaaa-aaaa-aaaa-aaaa-bbbbbbbbbbbb.json
  src/open_inwoner/apimock/apis/openklant-read/contactmomenten/klantcontactmomenten.json
  src/open_inwoner/apimock/apis/openklant-read/contactmomenten/klantcontactmomenten/aaaaaaaa-aaaa-aaaa-aaaa-cccccccccccc.json
  src/open_inwoner/apimock/apis/openklant-read/contactmomenten/objectcontactmomenten/aaaaaaaa-aaaa-aaaa-aaaa-ddddddddddd.json
  src/open_inwoner/cms/cases/views/status.py
  src/open_inwoner/components/templatetags/file_tags.py
  src/open_inwoner/conf/base.py
  src/open_inwoner/conf/fixtures/django-admin-index.json
  src/open_inwoner/openklant/admin.py
  src/open_inwoner/openklant/migrations/0009_klantcontactmomentanswer.py
  src/open_inwoner/openklant/models.py
  src/open_inwoner/openklant/tests/data.py
  src/open_inwoner/openklant/tests/factories.py
  src/open_inwoner/openklant/tests/test_helpers.py
  src/open_inwoner/openklant/tests/test_views.py
  src/open_inwoner/openklant/wrap.py
  src/open_inwoner/openzaak/tests/test_case_detail.py
  src/open_inwoner/scss/components/Card/Card.scss
  src/open_inwoner/templates/pages/contactmoment/list.html
  src/open_inwoner/templates/pages/questions/questions.html
  src/open_inwoner/utils/time.py
Labels: release 1.15

#1097 [#2232] Updating translations for release 1.15
  src/open_inwoner/conf/locale/nl/LC_MESSAGES/django.mo
  src/open_inwoner/conf/locale/nl/LC_MESSAGES/django.po
  src/open_inwoner/conf/parts/maileditor.py
Labels: release 1.15

#1100 [#2234] Fix subject for questions without e-suite code mapping
  src/open_inwoner/accounts/views/contactmoments.py
  src/open_inwoner/openklant/tests/test_views.py
Labels: release 1.15

#1120 :bug: [#2280/2269] Properly catch errors when fetching openstaande taken
  src/open_inwoner/cms/plugins/cms_plugins/userfeed.py
  src/open_inwoner/openzaak/clients.py
  src/open_inwoner/userfeed/feed.py
  src/open_inwoner/userfeed/hooks/external_task.py
  src/open_inwoner/userfeed/tests/test_external_tasks.py
  src/open_inwoner/userfeed/tests/test_feed.py
Labels: release 1.15.2

#1115 [#2277] Use first OIP subject for questions as fallback
  src/open_inwoner/accounts/views/contactmoments.py
  src/open_inwoner/openklant/tests/test_views.py
Labels: release 1.15.2

#1125 [#2170] Fixed issue with profile_page_is_published() & get_active_app_names() CMS helpers
  src/open_inwoner/accounts/tests/test_contact_views.py
  src/open_inwoner/accounts/tests/test_profile_views.py
  src/open_inwoner/cms/tests/cms_tools.py
  src/open_inwoner/cms/tests/test_page_display.py
  src/open_inwoner/cms/utils/page_display.py
Labels: release 1.15.2
