Repository maykinmedia/open-inwoner, pull requests merged in 2024-06, with the labels that each got.

#1239 [#2529] Expose yubin logs to the admin panel
  src/open_inwoner/conf/base.py
  src/open_inwoner/conf/fixtures/django-admin-index.json
  src/open_inwoner/mail/admin.py
  src/open_inwoner/mail/apps.py
  src/open_inwoner/utils/admin.py
Labels: release 1.17.2

#1236 [#2523] Prevent display of unpublished pages
  src/open_inwoner/pdc/tests/test_product.py
  src/open_inwoner/pdc/views.py
Labels: release 1.17.2

#1243 🐛 [#2530] Implement qmatic appointments using publicId
  src/open_inwoner/accounts/tests/test_profile_views.py
  src/open_inwoner/apimock/apis/qmatic/appointment/customers/identify;email=foo@bar.org.json
  src/open_inwoner/apimock/apis/qmatic/calendar-api/v1/customers/externalId/foo@bar.org/appointments.json
  src/open_inwoner/apimock/apis/qmatic/calendar-backend/public/api/v1/customers/12345/appointments.json
  src/open_inwoner/cms/plugins/tests/test_appointments.py
  src/open_inwoner/qmatic/client.py
  src/open_inwoner/qmatic/migrations/0004_alter_qmaticconfig_service.py
  src/open_inwoner/qmatic/models.py
  src/open_inwoner/qmatic/tests/data.py
  src/open_inwoner/qmatic/tests/factories.py
  src/open_inwoner/templates/cms/plugins/appointments/appointments.html
  src/open_inwoner/templates/pages/profile/appointments.html
Labels: release 1.17.3

#1249 :bug: [#2544] Added quickfix for non-URL dependent tab panels
  src/open_inwoner/scss/components/TabPanel/TabPanel.scss
  src/open_inwoner/templates/pages/ssd/monthly_reports_list.html
  src/open_inwoner/templates/pages/ssd/yearly_reports_list.html
Labels: release 1.17.4

#1250 ♿ [#2365] Remove focus from final case status
  src/open_inwoner/scss/components/Status/_StatusList.scss
  src/open_inwoner/templates/pages/cases/statuses.html
Labels: Accessibility

#1255 ♿ [#2369] Add focus-style for custom file-input
  src/open_inwoner/components/templates/components/Form/FileInput.html
  src/open_inwoner/scss/components/Form/FileInput.scss
  src/open_inwoner/scss/views/App.scss
Labels: Accessibility

#1224 :wheelchair: [#2345] A11y replace disallowed heading tags in Cards
  src/open_inwoner/components/templates/components/Card/CategoryCard.html
  src/open_inwoner/components/templates/components/Card/RenderCard.html
  src/open_inwoner/scss/components/Card/Card.scss
  src/open_inwoner/templates/pages/profile/me.html
Labels: Accessibility

#1256 ♿ [#2352] Set meaningful order in cards with status-indicator
  src/open_inwoner/scss/components/Card/CardGrid.scss
  src/open_inwoner/scss/components/Cases/Cases.scss
  src/open_inwoner/templates/pages/cases/list_inner.html
Labels: Accessibility

#1257 ♿ [#2352] Remove faulty aria-label and add external link
  src/open_inwoner/utils/ckeditor.py
Labels: Accessibility

#1223 [#2503] Add dyslexia modus with NL-DesignSystem components
  package-lock.json
  src/open_inwoner/js/components/accessibility/change_font.js
  src/open_inwoner/js/components/accessibility/enlarge_font.js
  src/open_inwoner/scss/components/AccessibilityHeader/AccessibilityHeader.scss
  src/open_inwoner/scss/components/Header/Header.scss
  src/open_inwoner/scss/components/Header/PrimaryNavigation.scss
  src/open_inwoner/scss/components/Typography/H1.scss
  src/open_inwoner/scss/components/Typography/H2.scss
  src/open_inwoner/scss/components/Typography/H3.scss
  src/open_inwoner/scss/components/Typography/H4.scss
  src/open_inwoner/scss/views/App.scss
Labels: Accessibility

#1252 ♿ [#2366] Add link purpose to document download links
  src/open_inwoner/components/templates/components/File/File.html
Labels: Accessibility

#1254 ♿ [#2344] Add text alternatives for meaningful status-icons
  src/open_inwoner/templates/pages/cases/statuses.html
Labels: Accessibility

#1260 ♿ [#2340] Header/footer logo use alt from image configuration
  src/open_inwoner/templates/master.html
Labels: Accessibility

#1258 ♿ [#2347] Add table-TH style/markup for product pages
  src/open_inwoner/scss/components/Table/Table.scss
  src/open_inwoner/utils/ckeditor.py
Labels: Accessibility

#1268 ♿ [#2357] Correct product-pages 400% zoom
  src/open_inwoner/scss/components/ReadMore/ReadMore.scss
Labels: Accessibility
