Repository maykinmedia/open-inwoner, pull requests merged in 2024-04, with the labels that each got.

#1113 [#2254] Fix toggle hide for case-related questions
  src/open_inwoner/js/components/card/ToggleHide.js
  src/open_inwoner/templates/pages/cases/status_inner.html
Labels: release 1.15.2

#1131 [#2283] Show categories plugin even if no other plugin is enabled
  src/open_inwoner/templates/pages/profile/me.html
Labels: release 1.15.3

#1147 [#2299] Due to django-digid-eherkenning issue #67
  requirements/base.txt
  requirements/ci.txt
  requirements/dev.txt
Labels: release 1.15.4

#1112 Make vragen detail conform to design
  src/open_inwoner/accounts/views/contactmoments.py
  src/open_inwoner/openklant/tests/test_views.py
  src/open_inwoner/scss/components/Contactmomenten/Contactmomenten.scss
  src/open_inwoner/templates/pages/contactmoment/detail.html
Labels: release 1.16

#1106 [#2106, #2203] Implemented 'contactform_confirmation' email
  src/open_inwoner/cms/cases/tests/test_contactform.py
  src/open_inwoner/cms/cases/views/status.py
  src/open_inwoner/cms/footer/tests/test_plugin.py
  src/open_inwoner/mail/service.py
  src/open_inwoner/mail/tests/test_service.py
  src/open_inwoner/openklant/admin.py
  src/open_inwoner/openklant/migrations/0012_openklantconfig_send_email_confirmation.py
  src/open_inwoner/openklant/models.py
  src/open_inwoner/openklant/tests/test_contactform.py
  src/open_inwoner/openklant/views/contactform.py
Labels: release 1.16

#1160 [#2259] Show case result in list view
  src/open_inwoner/openzaak/api_models.py
  src/open_inwoner/openzaak/cases.py
  src/open_inwoner/openzaak/tests/test_cases.py
  src/open_inwoner/utils/glom.py
  src/open_inwoner/utils/tests/test_glom.py
Labels: release 1.16

#1145 [#2274] Pass data in Haalcenntraal POST as JSON
  src/open_inwoner/haalcentraal/api.py
  src/open_inwoner/haalcentraal/tests/test_client.py
Labels: release 1.16

#1134 :lipstick: [#2272] Position indicator dot headings
  src/open_inwoner/components/templates/components/File/File.html
  src/open_inwoner/components/templates/components/File/FileTable.html
  src/open_inwoner/components/templates/components/Form/FileInput.html
  src/open_inwoner/js/components/form/FileInput.js
  src/open_inwoner/scss/components/Cases/CaseDetail.scss
  src/open_inwoner/scss/components/Cases/Cases.scss
  src/open_inwoner/scss/components/File/File.scss
  src/open_inwoner/scss/components/File/FileList.scss
  src/open_inwoner/scss/components/Form/FileInput.scss
  src/open_inwoner/scss/components/Grid/Grid.scss
  src/open_inwoner/scss/components/Typography/H2.scss
  src/open_inwoner/scss/components/UserFeed/UserFeed.scss
  src/open_inwoner/templates/cms/plugins/userfeed/userfeed.html
  src/open_inwoner/templates/pages/cases/status_inner.html
  src/open_inwoner/templates/pages/cases/status_outer.html
  src/open_inwoner/templates/pages/cases/statuses.html
Labels: release 1.16

#1154 [#2248] Make contact details editable for eHerkenning user
  src/open_inwoner/accounts/tests/test_profile_views.py
  src/open_inwoner/templates/pages/profile/edit.html
  src/open_inwoner/templates/pages/profile/me.html
Labels: release 1.16

#1137 :sparkles: [#2263] Setup configuration steps for authentication
  src/digid_eherkenning_oidc_generics/admin.py
  src/open_inwoner/conf/app/setup_configuration.py
  src/open_inwoner/conf/base.py
  src/open_inwoner/conf/production.py
  src/open_inwoner/configurations/bootstrap/auth.py
  src/open_inwoner/configurations/tests/bootstrap/files/digid-metadata.xml
  src/open_inwoner/configurations/tests/bootstrap/test_setup_auth_config.py
  src/open_inwoner/configurations/tests/bootstrap/test_setup_configuration.py
Labels: release 1.16

#1142 [#2260] Removed StatusTranslation model
  src/open_inwoner/accounts/tests/test_user.py
  src/open_inwoner/cms/cases/views/status.py
  src/open_inwoner/openzaak/admin.py
  src/open_inwoner/openzaak/api_models.py
  src/open_inwoner/openzaak/migrations/0047_delete_statustranslation.py
  src/open_inwoner/openzaak/models.py
  src/open_inwoner/openzaak/notifications.py
  src/open_inwoner/openzaak/resources/__init__.py
  src/open_inwoner/openzaak/resources/import_resource.py
  src/open_inwoner/openzaak/tests/factories.py
  src/open_inwoner/openzaak/tests/test_case_detail.py
  src/open_inwoner/openzaak/tests/test_cases.py
  src/open_inwoner/openzaak/tests/test_notification_data.py
  src/open_inwoner/openzaak/tests/test_notification_utils.py
  src/open_inwoner/openzaak/tests/test_status_translation.py
  src/open_inwoner/openzaak/utils.py
  src/open_inwoner/userfeed/hooks/case_status.py
  src/open_inwoner/userfeed/tests/hooks/test_case_status.py
  src/open_inwoner/utils/tests/test_translate.py
Labels: release 1.17

#1169 [#2328] Refactor tabpanels on login page
  src/open_inwoner/accounts/templates/registration/login.html
  src/open_inwoner/js/components/form/LoginForm.js
  src/open_inwoner/js/components/tab-panels/index.js
  src/open_inwoner/scss/components/TabPanel/TabPanel.scss
Labels: release 1.16.1

#1175 [#2339] Fix display of name infix in profile
  src/open_inwoner/accounts/tests/test_profile_views.py
  src/open_inwoner/templates/pages/profile/me.html
Labels: release 1.16.1

#1170 :sparkles: [#2303] Improvements/fixes for Laposta
  src/open_inwoner/accounts/tests/test_profile_views.py
  src/open_inwoner/accounts/views/profile.py
  src/open_inwoner/laposta/client.py
  src/open_inwoner/laposta/forms.py
  src/open_inwoner/laposta/migrations/0005_alter_lapostaconfig_limit_list_selection_to.py
  src/open_inwoner/laposta/models.py
  src/open_inwoner/laposta/tests/test_forms.py
  src/open_inwoner/templates/pages/profile/me.html
Labels: release 1.16.1
